# Experiment 7.3.9 — Pretrained A2 depth extension

Analysis-only notebook for finalized Exp7.3.9 artifacts. Training and probe fitting are performed by the experiment script/Slurm pipeline.

In [1]:
from pathlib import Path
import json
import pandas as pd
import matplotlib.pyplot as plt

ROOT = Path.cwd()
if ROOT.name == 'notebooks':
    ROOT = ROOT.parent
ART = ROOT / 'notebooks' / 'artifacts' / 'experiment_7_3_9_pretrained_a2_depth_extension' / 'pretrained_a2_depth_extension_v1'
ART

PosixPath('/home/zhaolongwei_umass_edu/projects/writingRing/notebooks/artifacts/experiment_7_3_9_pretrained_a2_depth_extension/pretrained_a2_depth_extension_v1')

In [2]:
manifest = json.loads((ART / 'manifest.json').read_text())
native_runs = pd.read_csv(ART / 'native_runs.csv')
native_summary = pd.read_csv(ART / 'native_summary.csv')
probe_runs = pd.read_csv(ART / 'probe_runs.csv')
probe_summary = pd.read_csv(ART / 'probe_summary.csv')
depth_contrasts = pd.read_csv(ART / 'depth_contrasts.csv')
bias_contrasts = pd.read_csv(ART / 'bias_contrasts.csv')
temporal_contrasts = pd.read_csv(ART / 'temporal_contrasts.csv')
layer_contrasts = pd.read_csv(ART / 'layer_contrasts.csv')
manifest

{'architecture_3layer': {'output': 'bias-free Linear 128->12',
  'shifts': [[2, 3, 4], [2, 3, 4], [2, 3, 4]],
  'widths': [128, 128, 128]},
 'cases': {'C0_a2_2layer': 'reuse Exp7.3 A2 checkpoint; no retraining',
  'C1_frozen_a2_train_l3': 'A2 W1/W2/Wout frozen; insert 128-neuron (2,3,4) L3 and train W3 only',
  'C2_c1_init_e2e_3layer': 'load selected C1 checkpoint; fresh Adam; epoch 0 is C1 candidate; unfreeze W1/W2/W3/Wout'},
 'counts': {'native_rows': 9,
  'new_training_runs': 6,
  'probe_rows': 96,
  'probe_tasks': 9},
 'experiment_id': 'experiment_7_3_9_pretrained_a2_depth_extension',
 'files': {'bias_contrasts': 'bias_contrasts.csv',
  'depth_contrasts': 'depth_contrasts.csv',
  'layer_contrasts': 'layer_contrasts.csv',
  'native_runs': 'native_runs.csv',
  'native_summary': 'native_summary.csv',
  'probe_runs': 'probe_runs.csv',
  'probe_summary': 'probe_summary.csv',
  'temporal_contrasts': 'temporal_contrasts.csv'},
 'probes': {'C_grid': [0.001, 0.01, 0.1, 1.0, 10.0],
  'affine': 'Exp7.3 StandardScaler(mean+scale) + intercept',
  'bias_modes': ['affine', 'no_bias'],
  'no_bias': 'train-only scale without centering + fit_intercept=False',
  'representations': ['wholecount', 'fixed250']},
 'protocol_version': 'pretrained_a2_depth_extension_v1',
 'question': 'Can a third 128-neuron (2,3,4) SNN layer improve an already trained Exp7.3 A2 hierarchy, first with the A2 backbone/output frozen and then with full end-to-end WCCE adaptation?',
 'seeds': [11, 23, 37],
 'source': {'architecture': '234x234',
  'experiment_id': 'experiment_7_3_training_strategy_decomposition',
  'method': 'A2_e2e_linear_wcce',
  'objective': 'wcce',
  'protocol_version': 'training_strategy_decomposition_v1'},
 'training': {'c2_epoch0_candidate': True,
  'c2_optimizer_state_reused': False,
  'checkpoint_rule': 'validation native BA primary, WCCE loss tiebreak',
  'max_epochs': 100,
  'min_epochs': 20,
  'objective': 'Exp7.3 A2 WCCE using valid-time mean Linear evidence',
  'patience': 30}}

## Native C0/C1/C2 performance

In [3]:
display(native_runs.sort_values(['case', 'seed']))
display(native_summary)
display(depth_contrasts)

,case,seed,architecture,training_scope,best_epoch,train_ba,val_ba,test_ba,test_accuracy,test_macro_f1
0,C0_a2_2layer,11,234x234,reused_exp7.3_A2,94,0.931670,0.523653,0.530632,0.547945,0.518542
1,C0_a2_2layer,23,234x234,reused_exp7.3_A2,89,0.917433,0.572264,0.596182,0.602740,0.589045
2,C0_a2_2layer,37,234x234,reused_exp7.3_A2,90,0.917487,0.566576,0.566691,0.575342,0.556651
3,C1_frozen_a2_train_l3,11,234x234x234,W3_only,9,0.866744,0.544060,0.479505,0.500000,0.459914
4,C1_frozen_a2_train_l3,23,234x234x234,W3_only,47,0.945803,0.563606,0.536384,0.541096,0.521352
5,C1_frozen_a2_train_l3,37,234x234x234,W3_only,10,0.836193,0.516679,0.410526,0.424658,0.391027
6,C2_c1_init_e2e_3layer,11,234x234x234,full_e2e_from_C1,0,0.866744,0.544060,0.479505,0.500000,0.459914
7,C2_c1_init_e2e_3layer,23,234x234x234,full_e2e_from_C1,18,0.977412,0.570881,0.530893,0.541096,0.522864
8,C2_c1_init_e2e_3layer,37,234x234x234,full_e2e_from_C1,58,0.987380,0.580267,0.502162,0.513699,0.485211

,case,architecture,training_scope,test_ba_mean,test_ba_std,test_ba_count,test_accuracy_mean,test_accuracy_std,test_accuracy_count,test_macro_f1_mean,test_macro_f1_std,test_macro_f1_count,best_epoch_mean,best_epoch_std,best_epoch_count
0,C0_a2_2layer,234x234,reused_exp7.3_A2,0.564502,0.032830,3,0.575342,0.027397,3,0.554746,0.035290,3,91.000000,2.645751,3
1,C1_frozen_a2_train_l3,234x234x234,W3_only,0.475472,0.063026,3,0.488584,0.059053,3,0.457431,0.065198,3,22.000000,21.656408,3
2,C2_c1_init_e2e_3layer,234x234x234,full_e2e_from_C1,0.504187,0.025754,3,0.518265,0.020925,3,0.489330,0.031676,3,25.333333,29.687259,3

,contrast,seed,left_case,right_case,test_ba_delta_pp
0,C1_minus_C0_insert_L3,11,C1_frozen_a2_train_l3,C0_a2_2layer,-5.112734
1,C1_minus_C0_insert_L3,23,C1_frozen_a2_train_l3,C0_a2_2layer,-5.979853
2,C1_minus_C0_insert_L3,37,C1_frozen_a2_train_l3,C0_a2_2layer,-15.616467
3,C2_minus_C1_e2e_adaptation,11,C2_c1_init_e2e_3layer,C1_frozen_a2_train_l3,0.000000
4,C2_minus_C1_e2e_adaptation,23,C2_c1_init_e2e_3layer,C1_frozen_a2_train_l3,-0.549034
5,C2_minus_C1_e2e_adaptation,37,C2_c1_init_e2e_3layer,C1_frozen_a2_train_l3,9.163545
6,C2_minus_C0_total_depth_gain,11,C2_c1_init_e2e_3layer,C0_a2_2layer,-5.112734
7,C2_minus_C0_total_depth_gain,23,C2_c1_init_e2e_3layer,C0_a2_2layer,-6.528888
8,C2_minus_C0_total_depth_gain,37,C2_c1_init_e2e_3layer,C0_a2_2layer,-6.452922

## Layer-wise representation probes

In [4]:
probe_view = probe_summary.sort_values(['case', 'layer', 'representation', 'bias_mode'])
display(probe_view)
display(layer_contrasts)

,case,layer,representation,bias_mode,test_balanced_accuracy_mean,test_balanced_accuracy_std,test_balanced_accuracy_count,test_accuracy_mean,test_accuracy_std,test_accuracy_count,test_macro_f1_mean,test_macro_f1_std,test_macro_f1_count,selected_C_mean,selected_C_std,selected_C_count
2,C0_a2_2layer,L1,fixed250,affine,0.544459,0.026306,3,0.557078,0.028516,3,0.545146,0.026375,3,0.700,0.519615,3
3,C0_a2_2layer,L1,fixed250,no_bias,0.551548,0.020307,3,0.563927,0.022017,3,0.546046,0.023109,3,0.010,0.000000,3
0,C0_a2_2layer,L1,wholecount,affine,0.600300,0.024233,3,0.609589,0.018122,3,0.590511,0.019052,3,0.700,0.519615,3
1,C0_a2_2layer,L1,wholecount,no_bias,0.564839,0.039974,3,0.573059,0.034474,3,0.556422,0.041466,3,0.700,0.519615,3
6,C0_a2_2layer,L2,fixed250,affine,0.579424,0.023212,3,0.593607,0.020925,3,0.578305,0.028892,3,0.370,0.547449,3
7,C0_a2_2layer,L2,fixed250,no_bias,0.580545,0.016500,3,0.595890,0.018122,3,0.575498,0.021290,3,3.370,5.741925,3
4,C0_a2_2layer,L2,wholecount,affine,0.586273,0.009744,3,0.600457,0.003954,3,0.581724,0.014811,3,0.010,0.000000,3
5,C0_a2_2layer,L2,wholecount,no_bias,0.540981,0.036907,3,0.547945,0.038135,3,0.532058,0.034654,3,6.670,5.767729,3
10,C1_frozen_a2_train_l3,L1,fixed250,affine,0.544459,0.026306,3,0.557078,0.028516,3,0.545146,0.026375,3,0.700,0.519615,3
11,C1_frozen_a2_train_l3,L1,fixed250,no_bias,0.551548,0.020307,3,0.563927,0.022017,3,0.546046,0.023109,3,0.010,0.000000,3
8,C1_frozen_a2_train_l3,L1,wholecount,affine,0.600300,0.024233,3,0.609589,0.018122,3,0.590511,0.019052,3,0.700,0.519615,3
9,C1_frozen_a2_train_l3,L1,wholecount,no_bias,0.564839,0.039974,3,0.573059,0.034474,3,0.556422,0.041466,3,0.700,0.519615,3
14,C1_frozen_a2_train_l3,L2,fixed250,affine,0.579424,0.023212,3,0.593607,0.020925,3,0.578305,0.028892,3,0.370,0.547449,3
15,C1_frozen_a2_train_l3,L2,fixed250,no_bias,0.580545,0.016500,3,0.595890,0.018122,3,0.575498,0.021290,3,3.370,5.741925,3
12,C1_frozen_a2_train_l3,L2,wholecount,affine,0.586273,0.009744,3,0.600457,0.003954,3,0.581724,0.014811,3,0.010,0.000000,3
13,C1_frozen_a2_train_l3,L2,wholecount,no_bias,0.540981,0.036907,3,0.547945,0.038135,3,0.532058,0.034654,3,6.670,5.767729,3
18,C1_frozen_a2_train_l3,L3,fixed250,affine,0.528426,0.030351,3,0.541096,0.036243,3,0.526542,0.028427,3,6.700,5.715768,3
19,C1_frozen_a2_train_l3,L3,fixed250,no_bias,0.544279,0.011230,3,0.554795,0.011863,3,0.534614,0.007974,3,3.700,5.474486,3
16,C1_frozen_a2_train_l3,L3,wholecount,affine,0.534018,0.025495,3,0.538813,0.025931,3,0.520605,0.029844,3,3.370,5.741925,3
17,C1_frozen_a2_train_l3,L3,wholecount,no_bias,0.512162,0.028878,3,0.520548,0.027397,3,0.495365,0.032131,3,0.010,0.000000,3
22,C2_c1_init_e2e_3layer,L1,fixed250,affine,0.548453,0.034308,3,0.561644,0.036243,3,0.544406,0.034429,3,0.700,0.519615,3
23,C2_c1_init_e2e_3layer,L1,fixed250,no_bias,0.555847,0.019446,3,0.568493,0.020548,3,0.549141,0.020549,3,0.010,0.000000,3
20,C2_c1_init_e2e_3layer,L1,wholecount,affine,0.589418,0.017774,3,0.602740,0.020548,3,0.583248,0.017676,3,0.400,0.519615,3
21,C2_c1_init_e2e_3layer,L1,wholecount,no_bias,0.541880,0.015667,3,0.557078,0.017237,3,0.533413,0.017227,3,0.400,0.519615,3
26,C2_c1_init_e2e_3layer,L2,fixed250,affine,0.570606,0.015951,3,0.586758,0.017237,3,0.564790,0.022398,3,0.007,0.005196,3
27,C2_c1_init_e2e_3layer,L2,fixed250,no_bias,0.571612,0.010198,3,0.589041,0.013699,3,0.564582,0.006907,3,0.004,0.005196,3
24,C2_c1_init_e2e_3layer,L2,wholecount,affine,0.569762,0.040960,3,0.584475,0.045605,3,0.566291,0.045136,3,0.340,0.571577,3
25,C2_c1_init_e2e_3layer,L2,wholecount,no_bias,0.556400,0.032637,3,0.563927,0.033787,3,0.551712,0.036107,3,3.370,5.741925,3
30,C2_c1_init_e2e_3layer,L3,fixed250,affine,0.552551,0.019765,3,0.568493,0.020548,3,0.542547,0.027564,3,0.700,0.519615,3
31,C2_c1_init_e2e_3layer,L3,fixed250,no_bias,0.576831,0.020003,3,0.589041,0.020548,3,0.567273,0.027245,3,3.700,5.474486,3
28,C2_c1_init_e2e_3layer,L3,wholecount,affine,0.525610,0.006678,3,0.534247,0.006849,3,0.505779,0.007078,3,0.700,0.519615,3
29,C2_c1_init_e2e_3layer,L3,wholecount,no_bias,0.524779,0.021303,3,0.536530,0.017237,3,0.508842,0.027134,3,6.670,5.767729,3

,case,seed,representation,bias_mode,L1,L2,L3,L3_minus_L2_pp
0,C1_frozen_a2_train_l3,11,fixed250,affine,0.523441,0.571629,0.551560,-2.006882
1,C1_frozen_a2_train_l3,11,fixed250,no_bias,0.535630,0.580235,0.556732,-2.350289
2,C1_frozen_a2_train_l3,11,wholecount,affine,0.577205,0.575830,0.514533,-6.129634
3,C1_frozen_a2_train_l3,11,wholecount,no_bias,0.530462,0.535766,0.502135,-3.363095
4,C1_frozen_a2_train_l3,23,fixed250,affine,0.535977,0.605531,0.539658,-6.587302
5,C1_frozen_a2_train_l3,23,fixed250,no_bias,0.544597,0.597197,0.534923,-6.227453
6,C1_frozen_a2_train_l3,23,wholecount,affine,0.598166,0.587870,0.562872,-2.499792
7,C1_frozen_a2_train_l3,23,wholecount,no_bias,0.555352,0.506960,0.544717,3.775738
8,C1_frozen_a2_train_l3,37,fixed250,affine,0.573960,0.561113,0.494061,-6.705239
9,C1_frozen_a2_train_l3,37,fixed250,no_bias,0.574418,0.564202,0.541182,-2.302004
10,C1_frozen_a2_train_l3,37,wholecount,affine,0.625529,0.595121,0.524648,-7.047258
11,C1_frozen_a2_train_l3,37,wholecount,no_bias,0.608702,0.580219,0.489635,-9.058442
12,C2_c1_init_e2e_3layer,11,fixed250,affine,0.536969,0.571629,0.551560,-2.006882
13,C2_c1_init_e2e_3layer,11,fixed250,no_bias,0.535630,0.580235,0.556732,-2.350289
14,C2_c1_init_e2e_3layer,11,wholecount,affine,0.570794,0.575830,0.532391,-4.343920
15,C2_c1_init_e2e_3layer,11,wholecount,no_bias,0.530462,0.541718,0.502135,-3.958333
16,C2_c1_init_e2e_3layer,23,fixed250,affine,0.521360,0.586021,0.572792,-1.322844
17,C2_c1_init_e2e_3layer,23,fixed250,no_bias,0.557494,0.574245,0.596737,2.249278
18,C2_c1_init_e2e_3layer,23,wholecount,affine,0.606200,0.607350,0.525401,-8.194930
19,C2_c1_init_e2e_3layer,23,wholecount,no_bias,0.535436,0.593799,0.544422,-4.937771
20,C2_c1_init_e2e_3layer,37,fixed250,affine,0.587030,0.554169,0.533299,-2.086941
21,C2_c1_init_e2e_3layer,37,fixed250,no_bias,0.574418,0.560356,0.577022,1.666667
22,C2_c1_init_e2e_3layer,37,wholecount,affine,0.591258,0.526107,0.519039,-0.706793
23,C2_c1_init_e2e_3layer,37,wholecount,no_bias,0.559742,0.533682,0.527780,-0.590243

## Bias and temporal-accessibility contrasts

In [5]:
display(bias_contrasts.sort_values(['case', 'seed', 'layer', 'representation']))
display(temporal_contrasts.sort_values(['case', 'seed', 'layer', 'bias_mode']))

,case,seed,layer,representation,affine,no_bias,affine_minus_no_bias_pp
0,C0_a2_2layer,11,L1,fixed250,0.523441,0.535630,-1.218920
1,C0_a2_2layer,11,L1,wholecount,0.577205,0.530462,4.674284
2,C0_a2_2layer,11,L2,fixed250,0.571629,0.580235,-0.860598
3,C0_a2_2layer,11,L2,wholecount,0.575830,0.535766,4.006410
4,C0_a2_2layer,23,L1,fixed250,0.535977,0.544597,-0.861985
5,C0_a2_2layer,23,L1,wholecount,0.598166,0.555352,4.281482
6,C0_a2_2layer,23,L2,fixed250,0.605531,0.597197,0.833333
7,C0_a2_2layer,23,L2,wholecount,0.587870,0.506960,8.091006
8,C0_a2_2layer,37,L1,fixed250,0.573960,0.574418,-0.045788
9,C0_a2_2layer,37,L1,wholecount,0.625529,0.608702,1.682692
10,C0_a2_2layer,37,L2,fixed250,0.561113,0.564202,-0.308858
11,C0_a2_2layer,37,L2,wholecount,0.595121,0.580219,1.490176
12,C1_frozen_a2_train_l3,11,L1,fixed250,0.523441,0.535630,-1.218920
13,C1_frozen_a2_train_l3,11,L1,wholecount,0.577205,0.530462,4.674284
14,C1_frozen_a2_train_l3,11,L2,fixed250,0.571629,0.580235,-0.860598
15,C1_frozen_a2_train_l3,11,L2,wholecount,0.575830,0.535766,4.006410
16,C1_frozen_a2_train_l3,11,L3,fixed250,0.551560,0.556732,-0.517191
17,C1_frozen_a2_train_l3,11,L3,wholecount,0.514533,0.502135,1.239871
18,C1_frozen_a2_train_l3,23,L1,fixed250,0.535977,0.544597,-0.861985
19,C1_frozen_a2_train_l3,23,L1,wholecount,0.598166,0.555352,4.281482
20,C1_frozen_a2_train_l3,23,L2,fixed250,0.605531,0.597197,0.833333
21,C1_frozen_a2_train_l3,23,L2,wholecount,0.587870,0.506960,8.091006
22,C1_frozen_a2_train_l3,23,L3,fixed250,0.539658,0.534923,0.473485
23,C1_frozen_a2_train_l3,23,L3,wholecount,0.562872,0.544717,1.815476
24,C1_frozen_a2_train_l3,37,L1,fixed250,0.573960,0.574418,-0.045788
25,C1_frozen_a2_train_l3,37,L1,wholecount,0.625529,0.608702,1.682692
26,C1_frozen_a2_train_l3,37,L2,fixed250,0.561113,0.564202,-0.308858
27,C1_frozen_a2_train_l3,37,L2,wholecount,0.595121,0.580219,1.490176
28,C1_frozen_a2_train_l3,37,L3,fixed250,0.494061,0.541182,-4.712093
29,C1_frozen_a2_train_l3,37,L3,wholecount,0.524648,0.489635,3.501360
30,C2_c1_init_e2e_3layer,11,L1,fixed250,0.536969,0.535630,0.133894
31,C2_c1_init_e2e_3layer,11,L1,wholecount,0.570794,0.530462,4.033258
32,C2_c1_init_e2e_3layer,11,L2,fixed250,0.571629,0.580235,-0.860598
33,C2_c1_init_e2e_3layer,11,L2,wholecount,0.575830,0.541718,3.411172
34,C2_c1_init_e2e_3layer,11,L3,fixed250,0.551560,0.556732,-0.517191
35,C2_c1_init_e2e_3layer,11,L3,wholecount,0.532391,0.502135,3.025586
36,C2_c1_init_e2e_3layer,23,L1,fixed250,0.521360,0.557494,-3.613400
37,C2_c1_init_e2e_3layer,23,L1,wholecount,0.606200,0.535436,7.076396
38,C2_c1_init_e2e_3layer,23,L2,fixed250,0.586021,0.574245,1.177642
39,C2_c1_init_e2e_3layer,23,L2,wholecount,0.607350,0.593799,1.355103
40,C2_c1_init_e2e_3layer,23,L3,fixed250,0.572792,0.596737,-2.394481
41,C2_c1_init_e2e_3layer,23,L3,wholecount,0.525401,0.544422,-1.902056
42,C2_c1_init_e2e_3layer,37,L1,fixed250,0.587030,0.574418,1.261239
43,C2_c1_init_e2e_3layer,37,L1,wholecount,0.591258,0.559742,3.151640
44,C2_c1_init_e2e_3layer,37,L2,fixed250,0.554169,0.560356,-0.618687
45,C2_c1_init_e2e_3layer,37,L2,wholecount,0.526107,0.533682,-0.757576
46,C2_c1_init_e2e_3layer,37,L3,fixed250,0.533299,0.577022,-4.372294
47,C2_c1_init_e2e_3layer,37,L3,wholecount,0.519039,0.527780,-0.874126

,case,seed,layer,bias_mode,fixed250,wholecount,fixed250_minus_wholecount_pp
0,C0_a2_2layer,11,L1,affine,0.523441,0.577205,-5.376360
1,C0_a2_2layer,11,L1,no_bias,0.535630,0.530462,0.516844
2,C0_a2_2layer,11,L2,affine,0.571629,0.575830,-0.420066
3,C0_a2_2layer,11,L2,no_bias,0.580235,0.535766,4.446942
4,C0_a2_2layer,23,L1,affine,0.535977,0.598166,-6.218920
5,C0_a2_2layer,23,L1,no_bias,0.544597,0.555352,-1.075452
6,C0_a2_2layer,23,L2,affine,0.605531,0.587870,1.766081
7,C0_a2_2layer,23,L2,no_bias,0.597197,0.506960,9.023754
8,C0_a2_2layer,37,L1,affine,0.573960,0.625529,-5.156926
9,C0_a2_2layer,37,L1,no_bias,0.574418,0.608702,-3.428447
10,C0_a2_2layer,37,L2,affine,0.561113,0.595121,-3.400766
11,C0_a2_2layer,37,L2,no_bias,0.564202,0.580219,-1.601732
12,C1_frozen_a2_train_l3,11,L1,affine,0.523441,0.577205,-5.376360
13,C1_frozen_a2_train_l3,11,L1,no_bias,0.535630,0.530462,0.516844
14,C1_frozen_a2_train_l3,11,L2,affine,0.571629,0.575830,-0.420066
15,C1_frozen_a2_train_l3,11,L2,no_bias,0.580235,0.535766,4.446942
16,C1_frozen_a2_train_l3,11,L3,affine,0.551560,0.514533,3.702686
17,C1_frozen_a2_train_l3,11,L3,no_bias,0.556732,0.502135,5.459749
18,C1_frozen_a2_train_l3,23,L1,affine,0.535977,0.598166,-6.218920
19,C1_frozen_a2_train_l3,23,L1,no_bias,0.544597,0.555352,-1.075452
20,C1_frozen_a2_train_l3,23,L2,affine,0.605531,0.587870,1.766081
21,C1_frozen_a2_train_l3,23,L2,no_bias,0.597197,0.506960,9.023754
22,C1_frozen_a2_train_l3,23,L3,affine,0.539658,0.562872,-2.321429
23,C1_frozen_a2_train_l3,23,L3,no_bias,0.534923,0.544717,-0.979437
24,C1_frozen_a2_train_l3,37,L1,affine,0.573960,0.625529,-5.156926
25,C1_frozen_a2_train_l3,37,L1,no_bias,0.574418,0.608702,-3.428447
26,C1_frozen_a2_train_l3,37,L2,affine,0.561113,0.595121,-3.400766
27,C1_frozen_a2_train_l3,37,L2,no_bias,0.564202,0.580219,-1.601732
28,C1_frozen_a2_train_l3,37,L3,affine,0.494061,0.524648,-3.058747
29,C1_frozen_a2_train_l3,37,L3,no_bias,0.541182,0.489635,5.154706
30,C2_c1_init_e2e_3layer,11,L1,affine,0.536969,0.570794,-3.382520
31,C2_c1_init_e2e_3layer,11,L1,no_bias,0.535630,0.530462,0.516844
32,C2_c1_init_e2e_3layer,11,L2,affine,0.571629,0.575830,-0.420066
33,C2_c1_init_e2e_3layer,11,L2,no_bias,0.580235,0.541718,3.851704
34,C2_c1_init_e2e_3layer,11,L3,affine,0.551560,0.532391,1.916972
35,C2_c1_init_e2e_3layer,11,L3,no_bias,0.556732,0.502135,5.459749
36,C2_c1_init_e2e_3layer,23,L1,affine,0.521360,0.606200,-8.484016
37,C2_c1_init_e2e_3layer,23,L1,no_bias,0.557494,0.535436,2.205780
38,C2_c1_init_e2e_3layer,23,L2,affine,0.586021,0.607350,-2.132937
39,C2_c1_init_e2e_3layer,23,L2,no_bias,0.574245,0.593799,-1.955475
40,C2_c1_init_e2e_3layer,23,L3,affine,0.572792,0.525401,4.739150
41,C2_c1_init_e2e_3layer,23,L3,no_bias,0.596737,0.544422,5.231574
42,C2_c1_init_e2e_3layer,37,L1,affine,0.587030,0.591258,-0.422772
43,C2_c1_init_e2e_3layer,37,L1,no_bias,0.574418,0.559742,1.467630
44,C2_c1_init_e2e_3layer,37,L2,affine,0.554169,0.526107,2.806222
45,C2_c1_init_e2e_3layer,37,L2,no_bias,0.560356,0.533682,2.667333
46,C2_c1_init_e2e_3layer,37,L3,affine,0.533299,0.519039,1.426074
47,C2_c1_init_e2e_3layer,37,L3,no_bias,0.577022,0.527780,4.924242

Interpretation targets:

- `C1 - C0`: value of an inserted L3 with A2 frozen.
- `C2 - C1`: gain/loss from coordinated E2E adaptation.
- `L3 - L2`: whether the new layer makes class information more directly accessible.
- `affine - no_bias`: dependence on class-specific constant offsets.
- `Fixed250 - WholeCount`: remaining dependence on explicit temporal position.